<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <ProjectReference Include="..\Rezber.Core\Rezber.Core.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" />  
    <PackageReference Include="AspNetCore.Identity.MongoDbCore" />  
  </ItemGroup>

</Project>
